language: node_js

node_js:
  - "5.2.0"

sudo: required

services:
  - docker
  - docker-compose

env:
  - TEST_DIR=server CLIENT_DIR=client DOCKER_DIR=docker/images

before_install:
  - npm install -g npm

before_script:
  - npm install -g grunt-cli
  - cd $DOCKER_DIR
  - make tutorials.tourguide-app
  - cd ../..

script:
  - cd $TEST_DIR && npm install && npm test
  - cd ../$CLIENT_DIR && npm install && npm test
